version: "3"

services:
  mariadb:
    volumes:
      - shared_databases:/var/lib/mysql
  php:
    environment:
      # https://wodby.com/docs/stacks/php/containers/#xdebug-local
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=MyServer
#      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ & Linux/Mac/Win
    volumes:
      - ./drupal:/var/www/html:cached

  nginx:
    volumes:
      - ./drupal:/var/www/html:cached

volumes:
  shared_databases:
    driver: local
